### ISSUE TITLE
Compile error while using Xcode 9.3

### ISSUE THREAD

**Issue by paper1111** [SOBotics/SwiftChatSE#9]
When compiling in a Swift 3.2 project, this error occurs:

```
/Users/xxxxx/Desktop/xcode/sockite/.build/checkouts/SwiftChatSE.git-382065480202907840/Sources/SwiftChatSE/ChatUser.swift:29:36: error: 'RawValue' is not a member type of 'ChatUser.Privileges'
                public init(rawValue: Privileges.RawValue) {
                                      ~~~~~~~~~~ ^
```
This only occurs after updating Xcode to 9.3, so probably related.

**Comment by NobodyNada** [comment]
Should have been fixed in [1c794c](https://github.com/SOBotics/SwiftChatSE/commit/1c794c1020ed348f4c93c24ea55243bef7da3fbb); did I forget to tag that release?

**Comment by NobodyNada** [comment]
Version 5.0.6 should work fine; what release are you on?

**Comment by Fortunate-MAN** [comment]
I can confirm that the latest release works fine on Xcode 9.3 with Swift 4.1 (using macOS 10.13.2). A SwiftChatSE update *should* solve your problem.

**Comment by NobodyNada** [comment]
Running `swift package update && swift package generate-xcodeproj` in the build folder should update SwiftChatSE and regenerate your Xcode project, provided your `Package.swift` allows the latest version.

**Comment by paper1111** [comment]
Updating the dependency solved the problem. Thanks!
